In [3]:
import numpy as np

# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

a = np.linspace(1, 10, num=10, dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
a3 = np.random.randint(1, 11, size=(5, 5))
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
a = np.random.random_sample((4, 4))
print(a)

[[0.91665092 0.41349329 0.48692635 0.90444113]
 [0.15329048 0.9900559  0.8784567  0.50337402]
 [0.65341164 0.03464008 0.45928385 0.16865697]
 [0.84085363 0.43778655 0.50228307 0.40283684]]


In [7]:
# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
a = np.random.randint(1, 11, size=(5))
b = np.random.randint(1, 11, size=(5))
c = a + b
d = a - b
k = a * b
print(a, b, c, d, k)

[1 7 8 9 5] [10  7  7  3  3] [11 14 15 12  8] [-9  0  1  6  2] [10 49 56 27 15]


In [8]:
# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
a = np.random.randint(-100, 100, size=(7))
b = np.random.randint(-100, 100, size=(7))
c = np.dot(a, b)
print(a, b, c)

[-55  -7 -28 -51   0  21 -55] [  3 -64  68  75 -21 -37 -43] -3858


In [9]:
# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
c = np.dot(a, b)
print(a, b, c)

[[10  6]
 [10  1]] [[ 8  4  8]
 [ 5  6 10]] [[110  76 140]
 [ 85  46  90]]


In [10]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
a = np.random.randint(1, 11, size=(3, 3))
b = np.linalg.inv(a)
print(a, b)

[[ 6  1  8]
 [ 6 10  7]
 [ 1  7 10]] [[ 0.10019646  0.09037328 -0.14341847]
 [-0.10412574  0.1021611   0.01178782]
 [ 0.06286837 -0.0805501   0.10609037]]


In [11]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
a = np.random.random_sample((4, 4))
b = a.T
print(a, b)

[[0.19368977 0.31970255 0.96414534 0.51125347]
 [0.12845752 0.5239085  0.50811624 0.62286788]
 [0.55642441 0.4418077  0.1863146  0.46211531]
 [0.42124882 0.95547537 0.84420428 0.50713938]] [[0.19368977 0.12845752 0.55642441 0.42124882]
 [0.31970255 0.5239085  0.4418077  0.95547537]
 [0.96414534 0.50811624 0.1863146  0.84420428]
 [0.51125347 0.62286788 0.46211531 0.50713938]]


In [12]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=(4))
c = np.dot(a, b)
print(a, b, c)

[[ 3  6  2  1]
 [ 1  6  7  3]
 [ 7 10  5  2]] [ 2 10  8  1] [ 83 121 156]


In [13]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
a = np.random.random_sample((2, 3))
b = np.random.random_sample((3,))
c = np.dot(a, b)
print(a, b, c)

[[0.45701405 0.41488972 0.81091031]
 [0.52521825 0.42024493 0.19251037]] [0.17786368 0.10870526 0.82757882] [0.7974791  0.29841759]


In [14]:
# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = a * b
print(a, b, c)

[[8 5]
 [9 3]] [[5 3]
 [9 8]] [[40 15]
 [81 24]]


In [15]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = np.dot(a, b)
print(a, b, c)

[[8 7]
 [7 4]] [[ 7 10]
 [ 3 10]] [[ 77 150]
 [ 61 110]]


In [16]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
a = np.random.randint(1, 101, size=(5, 5))
sum_el = a.sum()
print(sum_el)

1072


In [17]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
c = a - b
print(a, b, c)

[[ 5  8  1  7]
 [ 1  1  7  4]
 [ 5  1  3  8]
 [ 9  6 10  2]] [[ 9  4 10  5]
 [ 3  7  6  6]
 [ 1  4  6  6]
 [10  3  6 10]] [[-4  4 -9  2]
 [-2 -6  1 -2]
 [ 4 -3 -3  2]
 [-1  3  4 -8]]


In [18]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
a = np.random.random_sample((3, 3))
b = a.sum(axis=1)
c = b.reshape(3, 1)
print(a, c)

[[0.392425   0.46323675 0.34015437]
 [0.68380218 0.08324566 0.59588628]
 [0.87617181 0.83020976 0.39838917]] [[1.19581611]
 [1.36293413]
 [2.10477073]]


In [19]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
a = np.random.randint(-100, 100, size=(3, 4))
b = a * a
print(a, b)

[[-35  48  18 -15]
 [-46  50 -65 -88]
 [ 87  19  52   3]] [[1225 2304  324  225]
 [2116 2500 4225 7744]
 [7569  361 2704    9]]


In [20]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
a = np.random.randint(1, 51, size=(4,))
b = np.sqrt(a)
print(a, b)

[15  5 30 20] [3.87298335 2.23606798 5.47722558 4.47213595]
